<?php require "vendor/autoload.php";

$client = new GuzzleHttp\Client;

try {
    $response = $client->post('http://lrvlpssprt.test/oauth/token', [
        'form_params' => [
            'client_id'     => 2,            
            'client_secret' => 'rRv0wJdsvvqxbpWVZMZslhno1EuIu8FoPTcrbTo4', // generated by: php artisan passport:install
            'grant_type'    => 'password',
            'username'      => 'user@user.com',
            'password'      => '12345678',
            'scope'         => '*',
        ]
    ]);

    // You'd typically save this payload in the session
    $auth = json_decode( (string) $response->getBody() );

    $response = $client->get('http://lrvlpssprt.test/api/todos', [
        'headers' => [
            'Authorization' => 'Bearer '.$auth->access_token,
        ]
    ]);

    $todos = json_decode( (string) $response->getBody() );

    $todoList = "";
    foreach ($todos as $todo) {
        $todoList .= "<li>{$todo->task}".($todo->done ? '✅' : '')."</li>";
    }

    echo "<ul>{$todoList}</ul>";

} catch (GuzzleHttp\Exception\BadResponseException $e) {
    echo "Unable to retrieve access token.";
}